"""
Domain model for video episodes generated by Pixelle-Video.

Mirrors the podcast PodcastEpisode pattern:
  - Stored in SurrealDB table `video_episode`
  - `command` field links to the surreal-commands job
  - video_file stores a POSIX path relative to VIDEOS_FOLDER
"""

from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Optional, Union

from loguru import logger
from pydantic import Field, field_validator
from surrealdb import RecordID

from notebooke.database.repository import ensure_record_id, repo_query
from notebooke.domain.base import ObjectModel


class VideoEpisode(ObjectModel):
    """A video episode generated from notebook/source content."""

    table_name: ClassVar[str] = "video_episode"
    nullable_fields: ClassVar[set[str]] = {
        "video_file",
        "storyboard",
        "command",
        "notebook_id",
        "error_message",
        "video_type",
        "style",
        "character_id",
        "custom_prompt",
        "aspect_ratio",
    }

    # User-facing
    name: str = Field(..., description="Episode name / title")
    prompt: str = Field(..., description="Source text used for generation")
    notebook_id: Optional[str] = Field(
        default=None, description="Source notebook ID (optional)"
    )

    # Generation config snapshot (stored for display / re-run)
    llm_model: Optional[str] = Field(default=None, description="LLM model used")
    n_scenes: int = Field(default=5, description="Number of scenes")
    duration_minutes: int = Field(default=3, description="Target duration in minutes")
    image_workflow: Optional[str] = Field(default=None, description="Image generation workflow")
    visual_mode: str = Field(default="auto", description="Visual direction mode")
    tts_voice: str = Field(default="vi-VN-HoaiMyNeural", description="TTS voice used")
    language: Optional[str] = Field(default=None, description="Video language")
    video_type: Optional[str] = Field(default="summary", description="Type of video")
    style: Optional[str] = Field(default="auto", description="Visual template preset")
    character_id: Optional[str] = Field(default="AI", description="Character selection")
    custom_prompt: Optional[str] = Field(default=None, description="Additional custom instructions")
    aspect_ratio: Optional[str] = Field(
        default="16:9", description="Output aspect ratio"
    )

    # Output
    video_file: Optional[str] = Field(
        default=None,
        description=(
            "POSIX path to the generated MP4 relative to VIDEOS_FOLDER. "
            "None while the job is still running."
        ),
    )
    duration: Optional[float] = Field(
        default=None, description="Total video duration in seconds"
    )
    file_size: Optional[int] = Field(
        default=None, description="Video file size in bytes"
    )
    storyboard: Optional[Dict[str, Any]] = Field(
        default=None, description="Storyboard metadata snapshot"
    )
    error_message: Optional[str] = Field(
        default=None, description="Error message if generation failed"
    )

    # Job tracking
    command: Optional[Union[str, RecordID]] = Field(
        default=None, description="Link to surreal-commands job"
    )

    @field_validator("command", mode="before")
    @classmethod
    def parse_command(cls, value):
        if isinstance(value, str) and value:
            return ensure_record_id(value)
        return value

    def _prepare_save_data(self) -> dict:
        data = super()._prepare_save_data()
        if data.get("command") is not None:
            data["command"] = ensure_record_id(data["command"])
        return data

    async def get_job_status(self) -> Optional[str]:
        if not self.command:
            return None
        try:
            from surreal_commands import get_command_status

            status = await get_command_status(str(self.command))
            return status.status if status else "unknown"
        except Exception:
            return "unknown"

    async def get_job_detail(self) -> dict:
        if not self.command:
            return {"status": None, "error_message": None}
        try:
            from surreal_commands import get_command_status

            status = await get_command_status(str(self.command))
            if not status:
                return {"status": "unknown", "error_message": None}
                
            result_dict = status.result if isinstance(status.result, dict) else getattr(status.result, "model_dump", lambda: {})()
            error_message = getattr(status, "error_message", None) or result_dict.get("error_message")
            success = result_dict.get("success")
            job_status = status.status
            if job_status == "completed" and (success is False or error_message):
                job_status = "failed"
                
            return {
                "status": job_status,
                "error_message": error_message,
            }
        except Exception:
            return {"status": "unknown", "error_message": None}

    @classmethod
    async def get_job_details_for_commands(
        cls, command_ids: List[Union[str, RecordID]]
    ) -> Dict[str, dict]:
        """Batch-fetch job status for many commands in one query."""
        ids = [cid for cid in command_ids if cid]
        grouped: Dict[str, dict] = {}
        if not ids:
            return grouped
        try:
            result = await repo_query(
                "SELECT * FROM command WHERE id IN $command_ids",
                {"command_ids": [ensure_record_id(cid) for cid in ids]},
            )
        except Exception as e:
            logger.error(f"Error batch-fetching video command status: {e}")
            return grouped
        for row in result:
            output_data = row.get("output_data") or {}
            
            # Retrieve error_message and success flag from either the row itself (if unhandled exception)
            # or from the command's successful output_data if the command gracefully returned failure
            error_message = row.get("error_message") or output_data.get("error_message")
            success = output_data.get("success")
            
            grouped[str(row.get("id"))] = {
                "status": row.get("status", "unknown"),
                "error_message": error_message,
                "success": success,
            }
        return grouped
